name: sspi_web
description: SSPI  Admin Web

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


  cupertino_icons: ^1.0.2

  firebase_core:
  path: any
  firebase_storage:
  firebase_auth:
  cloud_firestore:
  get: ^4.6.5
  google_fonts: ^4.0.3
  image_picker: ^0.8.6+1
  flutter_svg: ^2.0.2
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0





flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icon/



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700